// PM2 Ecosystem — Heavenly Dreams Production Server
// Run: pm2 start ecosystem.config.js
// Save: pm2 save && pm2 startup
module.exports = {
  apps: [
    {
      name: "heavenlydreams-app",
      script: "server.ts",
      interpreter: "tsx",
      cwd: "/root/heavenlydreams",
      env: { NODE_ENV: "production", PORT: 3000 },
      max_memory_restart: "512M",
      restart_delay: 3000,
      max_restarts: 10,
    },
    {
      name: "heavenly-dreams-web",
      script: "dist/server.cjs",
      cwd: "/root/heavenly-dreams-web",
      env: { NODE_ENV: "production", PORT: 4173 },
      max_memory_restart: "512M",
      restart_delay: 3000,
      max_restarts: 10,
    },
    {
      name: "hd-admin",
      script: "dist/server.cjs",
      cwd: "/root/HD-ADMIN",
      env: { NODE_ENV: "production", PORT: 3001 },
      max_memory_restart: "512M",
      restart_delay: 3000,
      max_restarts: 10,
    },
    {
      name: "hd-crm",
      script: "dist/server.cjs",
      cwd: "/root/HD-CRM",
      env: { NODE_ENV: "production", PORT: 3002 },
      max_memory_restart: "512M",
      restart_delay: 3000,
      max_restarts: 10,
    },
    {
      name: "hd-brain",
      script: "dist/server.cjs",
      cwd: "/root/HD-BRAIN",
      env: { NODE_ENV: "production", PORT: 3003 },
      max_memory_restart: "512M",
      restart_delay: 3000,
      max_restarts: 10,
    },
    {
      name: "hd-rh",
      script: "dist/server.cjs",
      cwd: "/root/HD-RH",
      env: { NODE_ENV: "production", PORT: 3004 },
      max_memory_restart: "512M",
      restart_delay: 3000,
      max_restarts: 10,
    },
    {
      name: "hd-operations",
      script: "dist/server.cjs",
      cwd: "/root/HD-OPERATIONS",
      env: { NODE_ENV: "production", PORT: 3005 },
      max_memory_restart: "512M",
      restart_delay: 3000,
      max_restarts: 10,
    },
    {
      name: "hd-central-api",
      script: "apps/api/dist/main.js",
      cwd: "/root/heavenly-central",
      env: { NODE_ENV: "production", PORT: 3006 },
      max_memory_restart: "512M",
      restart_delay: 3000,
      max_restarts: 10,
    },
    {
      name: "hd-central-web",
      script: "npx",
      args: "next start -p 4001",
      cwd: "/root/heavenly-central/apps/web",
      env: { NODE_ENV: "production" },
      max_memory_restart: "1G",
      restart_delay: 3000,
      max_restarts: 10,
    },
  ],
};
